image: ubuntu:latest

stages:
  - build
  - test

make:
  stage: build
  script:
    - apt-get -y update
    - apt-get -y install make git
    - make world

test:
  stage: test
  script:
    - echo "how does one test dotfiles?"
