image: ubuntu:latest

stages:
  - build
  - test

before_script:
  - apt-get -y update
  - apt-get -y install make git

make:
  stage: build
  script:
    - make all

test:
  stage: test
  script:
    - echo "how does one test dotfiles?"
